name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        sudo apt-get install ruby-full
        sudo gem install ceedling
    - name: build
      run: ceedling release
    - name: upload executable
        uses: actions/upload-artifact@v1
        with:
          name: lru-cache
          path: build/release/lru-cache.out
